### ISSUE TITLE
make this a maven repository

### ISSUE THREAD

**Issue by theScrabi** [microg/JGoogle#1]
If JGoogle was a maven repository I could use import it directly.

**Comment by timofonic** [comment]
Is this repository alive? :O

**Comment by mar-v-in** [comment]
No, I haven't touched this code for over 2 years and I don't even know if it is still working. The approach to use a generic Java library inside Android turned out to be a bad idea, because it actually makes some things harder. This is why JGoogle (and JGooglePlay) are not used in any microg projects today.

**Comment by spacekitteh** [comment]
@mar-v-in So what actually talks to to the GCM cloud server?

**Comment by mar-v-in** [comment]
Details on the GCM client code in GmsCore can be found in its repo: https://github.com/microg/android_packages_apps_GmsCore/tree/master/play-services-core/src/main/java/org/microg/gms/gcm
